AWSTemplateFormatVersion: '2010-09-09'
Description: Desplegar una instancia de EC2 con Ubuntu 22.04 LTS y Docker

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Tipo de instancia EC2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nombre de la llave SSH para acceder a la instancia

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0b0af3577fe5e3532  #Ubuntu 22.04 LTS
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y docker.io
          systemctl start docker
          systemctl enable docker
          apt-get install -y docker-compose
          git clone https://github.com/andresprogramacion123/prueba-tecnica-btg-desarrollador-backend-python.git
          cd prueba-tecnica-btg-desarrollador-backend-python
          docker compose up --build -d

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso SSH y HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0